---
- name: Create users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    shell: /bin/zsh
  loop: "{{ users }}"
  become: true
  become_user: root

### Need to add SSH key
- name: Make .ssh folder
  file:
    path: "/home/{{ item.username }}/.ssh"
    state: directory
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ users }}"

- name: Generate OpenSSH key pair
  openssh_keypair:
    path: "/home/{{ item.username }}/.ssh/github"
    type: rsa
    size: 2048
    state: present
  register: ssh_keypair
  loop: "{{ users }}"

- name: Add public key to authorized_keys
  authorized_key:
    user: thomasdriscoll
    key: "{{ ssh_keypair.public_key }}"

### Being config cloning
- name: Clone neovim-config
  git:
    repo: git@github.com:thomasdriscoll/neovim-config.git
    dest: "/home/{{ item.username }}/.config/nvim"
  loop: "{{ users }}"
  become: true
  become_user: "{{ item.username }}"


- name: Clone dotfiles
  git:
    repo: git@github.com:thomasdriscoll/dotfiles.git
    dest: "/home/{{ item.username }}/dotfiles"
    separate_git_dir: "~/.cfg"
  loop: "{{ users }}"
  become: true
  become_user: "{{ item.username }}"

- name: Move dotfiles to next level up
  shell: mv -f /home/{{ item.username }}/dotfiles/* /home/{{ item.username }}/
  loop: "{{ users }}"
  become: true
  become_user: "{{ item.username }}"

- name: Update Git working tree
  command: git --git-dir=/home/{{ item.username }}/.cfg --work-tree=/home/{{ item.username }} config core.worktree /home/{{ item.username }}
  loop: "{{ users }}"
  become: true
  become_user: "{{ item.username }}"
