---
- name: Create users
  ansible.builtin.user:
    name: "{{ _user.username }}"
    password: "{{ _user.password | password_hash('sha512', _user.username) }}"
    groups: "{{ _user.groups }}"
    shell: /bin/zsh
    update_password: always
  become: true
  become_user: root

### Need to add SSH key
- name: Make .ssh folder
  ansible.builtin.file:
    path: "/home/{{ _user.username }}/.ssh"
    state: directory
    mode: "0700"
  become: true
  become_user: "{{ _user.username }}"

- name: Generate OpenSSH key pair
  community.crypto.openssh_keypair:
    path: "/home/{{ _user.username }}/.ssh/github"
    type: rsa
    size: 2048
    state: present
  register: ssh_keypair


### Being config cloning
- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/thomasdriscoll/dotfiles.git
    dest: "/home/{{ _user.username }}/dotfiles"
    separate_git_dir: "~/.cfg"
    # noqa: latest
  become: true
  become_user: "{{ _user.username }}"

- name: Move files one level up
  ansible.builtin.command: "ls -a /home/{{ _user.username }}/dotfiles"
  register: dotfiles_to_move
  changed_when: false

- name: Move files to destination
  ansible.builtin.command: >
    mv
    "/home/{{ _user.username }}/dotfiles/{{ iterator }}"
    "/home/{{ _user.username }}/"
  loop: "{{ dotfiles_to_move.stdout_lines[2:] }}"
  loop_control:
    loop_var: iterator
  changed_when: true

- name: Clone neovim-config
  ansible.builtin.git:
    repo: https://github.com/thomasdriscoll/neovim-config.git
    dest: "/home/{{ _user.username }}/.config/nvim"
    # noqa: latest
  become: true
  become_user: "{{ _user.username }}"

- name: Update sys-git working tree
  # noqa: command-instead-of-module
  ansible.builtin.command: >
    git --git-dir=/home/{{ _user.username }}/.cfg
    --work-tree=/home/{{ _user.username }}
    config core.worktree /home/{{ _user.username }}
  become: true
  become_user: "{{ _user.username }}"
  changed_when: true

- name: Add AUR ansible collection
  ansible.builtin.command: ansible-galaxy collection install kewlfft.aur
  become: true
  become_user: "{{ _user.username }}"
  changed_when: true

- name: Create Projects directory
  ansible.builtin.file:
    path: "/home/{{ _user }}/Projects"
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ _user.username }}"

- name: Delete dotfiles direcotry
  ansible.builtin.file:
    path: "/home/{{ _user }}/dotfiles"
    state: absent
  become: true
  become_user: "{{ _user.username }}"
