---
- name: Create users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    shell: /bin/zsh
  loop: "{{ users }}"
  become: true
  become_user: root

- name: Clone dotfiles
  git:
    repo: git@github.com:thomasdriscoll/dotfiles.git
    dest: "/home/{{ item.username }"
    separate_git_dir: "~/.cfg"
  loop: "{{ users }}"
  become: true
  become_user: "{{ item.username }}"
