---
- name: Create users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    shell: /bin/zsh
  loop: "{{ users }}"
  become: true
  become_user: root

- name: Clone dotfiles
  git:
    repo: https://github.com/thomasdriscoll/arch-linux-ansible.git
    dest: "/home/{{ item.username }}/dotfiles"
    separate_git_dir: "~/.cfg"
  loop: "{{ users }}"
  become: true
  become_user: "{{ item.username }}"

- name: Move dotfiles to next level up
  command: mv -f /home/{{ item.username }}/dotfiles/* /home/{{ item.username }}/
  loop: "{{ users }}"
  become: true
  become_user: "{{ item.username }}"

- name: Update Git working tree
  command: git --git-dir=/home/{{ item.username }}/.cfg --work-tree=/home/{{ item.username }} config core.worktree /home/{{ item.username }}
  loop: "{{ users }}"
  become: true
  become_user: "{{ item.username }}"
