---
- name: Set up LVM with dm-crypt
  hosts: localhost
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Create physical volume
      # Create a physical volume on the specified disk
      command: pvcreate "{{ disk }}"

    - name: Create volume group
      # Create a volume group using the physical volume
      lvg:
        vg: "{{ vg_name }}"
        pvs: "{{ disk }}"

    - name: Create logical volume for root
      # Create a logical volume within the volume group
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ root_lv }}"
        size: "{{ root_lv_size }}"


    - name: Set up dm-crypt on logical volume
      cryptsetup:
        name: "{{ vg_name }}-crypt"
        state: present
        device: "/dev/{{ vg_name }}/{{ root_lv }}"
        cipher: aes-xts-plain64
        key_size: 512
        passphrase: "{{ passphrase }}"
      become: true
      become_user: root

    - name: Open encrypted logical volume
      # Open the encrypted logical volume with the specified root_crypt_name and passphrase
      command: echo "{{ passphrase }}" | cryptsetup luksOpen "/dev/{{ vg_name }}/{{ root_lv }}" "{{ root_crypt_name }}"
      become_user: root
      become: yes
      args:
        stdin: yes

    - name: Create encrypted filesystem
      # Create a filesystem on the encrypted volume
      filesystem:
        fstype: ext4  # Replace with the desired filesystem type (e.g., ext4, xfs, etc.)
        dev: "/dev/mapper/{{ root_crypt_name }}"

    - name: Mount encrypted filesystem
      # Mount the encrypted filesystem to the specified mount path
      mount:
        path: /mnt  # Replace with the desired mount path
        src: "/dev/mapper/{{ root_crypt_name }}"
        fstype: ext4  # Replace with the desired filesystem type
        state: mounted

    # Additional tasks can be added for further configuration or customization

