---
- name: Configure user
  hosts: localhost
  gather_facts: false
  become: yes

  tasks:
    - name: Clone dotfiles
      git:
        repo: git@github.com:thomasdriscoll/dotfiles.git
        dest: "/home/{_user}"
        separate_git_dir: "~/.cfg"
