---
- name: Desktop configuration
  hosts: localhost
  become: true
  become_user: root

  vars_files:
    - ./variables/kde.yml

  tasks:
    - name: Update pacman
      command: pacman -Syu --noconfirm

    - name: Install Xorg environment
      command: "pacman -S --noconfirm {{ item }}"
      loop: "{{ xorg_packages }}"

    - name: Install Plasma
      command: pacman -S --noconfirm plasma

    - name: Install Display Manager (SDDM)
      command: pacman -S --noconfirm sddm

    - name: Enable SDDM
      service:
        name: sddm
        state: stopped
        enabled: true

    - name: Install additional packages
      command: "pacman -S --noconfirm {{ item }}"
      loop: "{{ desktop_packages }}"
