---
- name: i3 + KDE configuration
  hosts: localhost

  vars_prompt:
    - name: selected_role
      prompt: "Choose a desktop configuration (valid choices: kde_i3_desktop)"
      private: no
      validate: "^(kde_i3_desktop)$"

  tasks:
    - name: Use kde/i3 role
      include_role:
        name: "kde_i3_desktop"
      when: selected_role == "kde_i3_desktop"
