---
- name: Desktop configuration
  hosts: localhost
  become: true
  become_user: root

  vars_files:
    - kde.yml

  tasks:
    - name: Update pacman
      ansible.builtin.command: pacman -Syu --noconfirm
      changed_when: true

    - name: Install Xorg environment
      ansible.builtin.command: "pacman -S --noconfirm {{ item }}"
      loop: "{{ xorg_packages }}"
      changed_when: true

    - name: Install Plasma
      ansible.builtin.command: pacman -S --noconfirm plasma
      changed_when: true

    - name: Install Display Manager (SDDM)
      ansible.builtin.command: pacman -S --noconfirm sddm
      changed_when: true

    - name: Enable SDDM
      ansible.builtin.service:
        name: sddm
        state: stopped
        enabled: true
      changed_when: true

    - name: Install additional packages
      ansible.builtin.command: "pacman -S --noconfirm {{ item }}"
      loop: "{{ desktop_packages }}"
      changed_when: true
