---
- name: Post-install system configuration
  hosts: localhost
  become: true

  vars_files:
    - ../variables/sys-config-vars.yml
    - ../variables/users.yml

  tasks:
    - name: Update pacman first
      command: pacman -Syu --noconfirm
      become: true
      become_user: root

  ### Create and configure users and permissions
    - name: Configure users
      include_role:
        name: configure_user
      vars:
        _user: "{{ item }}"
      loop: "{{ users }}"

    - name: Uncomment NOPASSWD for wheel group
      lineinfile:
        path: /etc/sudoers
        regex: '^%wheel\s+ALL=\(ALL\)\s+NOPASSWD: ALL$'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        backup: yes
        state: present
        validate: 'visudo -cf %s'
      become: true
      become_user: root

  ### Set firewall rules
    - name: Configure UFW Default Policies
      ufw:
        policy: '{{ item.policy }}'
        direction: '{{ item.direction }}'
      with_items:
        - { policy: 'deny', direction: 'incoming' }
        - { policy: 'allow', direction: 'outgoing' }


    - name: Manage UFW rules
      ufw:
        rule: "{{ item.rule }}"
        app: "{{ item.app }}"
        from: "{{ item.from }}"
      loop:
        - { rule: allow, app: 'Deluge', from: 'Anywhere' }
        - { rule: limit, app: 'SSH', from: 'Anywhere' }
        - { rule: allow, app: 'deluge', from: 'Anywhere (v6)' }
        - { rule: allow, app: 'SSH', from: 'Anywhere (v6)' }
        - { rule: allow, app: 'any', from: '192.168.0.0/24' }

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Start NetworkManager
      service:
        name: NetworkManager
        state: started
        enabled: true

  ### Additional security
    - name: Start AppArmor service
      service:
        name: apparmor
        state: started
        enabled: true
